config-version = 2

# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
# after-startup-command = ['exec-and-forget sketchybar']

# ----------- ## SKETCHYBAR

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
# after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# ----------- ## SKETCHYBAR

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 16
    inner.vertical =   16
    outer.left =       16
    outer.bottom =     16
    outer.top =        [{monitor.dell = 40 }, 16]
    outer.right =      16

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    # ctrl-0 = 'resize width +100'
    # ctrl-shift-0 = 'resize width -100'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    # alt-tab = 'focus right --boundaries workspace --boundaries-action wrap-around-the-workspace --ignore-floating'
    # alt-shift-tab = 'focus left --boundaries workspace --boundaries-action wrap-around-the-workspace --ignore-floating'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-m = ['exec-and-forget hs -c "showScreenBorder({color={red=0.3,green=0.5,blue=1,alpha=1},label=[[hjkl=move|shift=join|alt=swap|d=autosize|space=scripts|w=width|u=height]]})"', 'mode service']

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes

[mode.scripts.binding]
    backspace = ['exec-and-forget hs -c "showScreenBorder({color={red=0.3,green=0.5,blue=1,alpha=1},label=[[hjkl=move|shift=join|alt=swap|d=autosize]]})"', 'mode service']
    esc = ['exec-and-forget hs -c "hideScreenBorder()"', 'mode main']
    s = ['exec-and-forget hs -c "hideScreenBorder()"', 'exec-and-forget /Users/tobbe/dev/dotfiles/scripts/toggle-hazeover.sh', 'mode main']
    b = ['exec-and-forget pkill borders || borders', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']

    # hydra mode (dont exit on trigger)
    h = [ 'move left']
    j = [ 'move down']
    k = [ 'move up']
    l = [ 'move right']

    # never merges or breaks windows out of containers
    alt-h = 'swap left'
    alt-j = 'swap down'
    alt-k = 'swap up'
    alt-l = 'swap right'

    shift-h = ['join-with left']
    shift-j = ['join-with down']
    shift-k = ['join-with up']
    shift-l = ['join-with right']


[mode.service.binding]
    esc = ['exec-and-forget hs -c "hideScreenBorder()"', 'reload-config', 'mode main']
    space = ['exec-and-forget hs -c "showScreenBorder({color={red=1,green=0.3,blue=0.3,alpha=1},label=[[s=hazeover|b=borders|hjkl=move]]})"', 'mode scripts']

    c = ['flatten-workspace-tree']
    r = ['exec-and-forget hs -c "hideScreenBorder()"', 'exec-and-forget zsh ~/dev/dotfiles/reload.sh', 'mode main']

    a = ['layout accordion']
    t = ['layout tiling']

    b = ['balance-sizes']
    d = ['exec-and-forget hs -c "autoResize()"', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']
    e = ['exec-and-forget hs -c "resizeToPercent(48)"', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']

    f = ['layout floating', 'exec-and-forget hs -c "centerFloating(40, 60)"', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']

    v = ['layout h_tiles']
    s = ['layout v_tiles']

    tab = ['focus-monitor next --wrap-around', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']

    w = 'resize width +100'
    shift-w = 'resize width -100'
    u = 'resize height +100'
    shift-u = 'resize height -100'

    # might merge lonly window with container when moving (when on the edge)
    h = [ 'move left','exec-and-forget hs -c "hideScreenBorder()"', 'mode main']
    j = [ 'move down', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']
    k = [ 'move up', 'exec-and-forget hs -c "hideScreenBorder()"', 'mode main']
    l = [ 'move right','exec-and-forget hs -c "hideScreenBorder()"', 'mode main']

    # never merges or breaks windows out of containers
    alt-h = 'swap left'
    alt-j = 'swap down'
    alt-k = 'swap up'
    alt-l = 'swap right'


    shift-h = ['join-with left']
    shift-j = ['join-with down']
    shift-k = ['join-with up']
    shift-l = ['join-with right']

    1 = ['workspace 1']
    2 = ['workspace 2']
    3 = ['workspace 3']
    4 = ['workspace 4']
    5 = ['workspace 5']
    6 = ['workspace 6']
    7 = ['workspace 7']
    8 = ['workspace 8']
    9 = ['workspace 9']

    shift-1 = ['move-node-to-workspace 1']
    shift-2 = ['move-node-to-workspace 2']
    shift-3 = ['move-node-to-workspace 3']
    shift-4 = ['move-node-to-workspace 4']
    shift-5 = ['move-node-to-workspace 5']
    shift-6 = ['move-node-to-workspace 6']
    shift-7 = ['move-node-to-workspace 7']
    shift-8 = ['move-node-to-workspace 8']
    shift-9 = ['move-node-to-workspace 9']

    #down = 'volume down'
    #up = 'volume up'
    #shift-down = ['volume set 0']




# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
9 = 'secondary'

# https://nikitabobko.github.io/AeroSpace/goodies#popular-apps-ids
# aerospace list-apps

# https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
[[on-window-detected]]
    if.app-name-regex-substring = 'code|iTerm2|Firefox'
    run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
    if.app-name-regex-substring = 'kitty'
    run = ['layout tiling', 'move-node-to-workspace 1']
    # run = [ 'exec-and-forget /Users/tobbe/dev/dotfiles/scripts/aerospace-resize-to-percent.sh 64'] # this script is faster for startup, and so we dont have to sleep

[[on-window-detected]]
    if.app-name-regex-substring = 'notion|obsidian|Simulator|figma|trello'
    run = ['move-node-to-workspace 9', "layout accordion"]

[[on-window-detected]]
    if.app-name-regex-substring = 'Preview|Shottr'
    run = ['layout floating', 'exec-and-forget hs -c "centerFloating(40, 60)"']

[[on-window-detected]]
    if.app-name-regex-substring = 'finder|moom|Karabiner-Elements|Karabiner-EventViewer'
    run = ['layout floating', 'move-node-to-workspace 1']

[[on-window-detected]]
    if.app-name-regex-substring = 'slack|mail|discord|Messages'
    run = ['layout floating', 'move-node-to-workspace 2', 'exec-and-forget hs -c "centerFloating(40, 60)"']

[[on-window-detected]]
    if.app-name-regex-substring = 'sublime merge'
    run = ['move-node-to-workspace 3', 'layout tiling']

[[on-window-detected]]
    if.app-name-regex-substring = 'spotify'
    run = ['move-node-to-workspace 4', 'layout tiling']

[[on-window-detected]]
    if.app-name-regex-substring = 'ChapMacOS|claude'
    run = ['layout floating', 'move-node-to-workspace 5', 'exec-and-forget hs -c "centerFloating(40, 60)"']
