keybinding:
  universal:
    quit: q
    quit-alt1: <c-q>
git:
  paging:
    pager: delta --dark --paging=never
    # pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
